const tasks = [
  {
    id: 1,
    task: "Exercise",
    description: "Do five push-ups",
    difficulty: "medium",
    type: "selfcare",
  },
  {
    id: 2,
    task: "Study",
    description: "Read chapters 1 and 2",
    difficulty: "medium",
    type: "study",
  },
  {
    id: 3,
    task: "Meditate",
    description: "Meditate for 10 minutes",
    difficulty: "easy",
    type: "selfcare",
  },
  {
    id: 4,
    task: "Project Work",
    description: "Complete project report",
    difficulty: "hard",
    type: "study",
  },
  {
    id: 5,
    task: "Cook Dinner",
    description: "Prepare a healthy meal",
    difficulty: "medium",
    type: "other",
  },
  {
    id: 6,
    task: "Go for a Walk",
    description: "Walk for 30 minutes",
    difficulty: "easy",
    type: "selfcare",
  },
  {
    id: 7,
    task: "Practice Coding",
    description: "Solve 5 coding challenges",
    difficulty: "hard",
    type: "study",
  },
  {
    id: 8,
    task: "Read a Book",
    description: "Read a chapter from my favorite book",
    difficulty: "easy",
    type: "other",
  },
  {
    id: 9,
    task: "Code a game",
    description: "work",
    difficulty: "hard",
    type: "work",
  },
  {
    id: 10,
    task: "Learn game design",
    description: "work",
    difficulty: "hard",
    type: "study",
  },
  {
    id: 11,
    task: "Journal",
    description: "Write down thoughts for the day",
    difficulty: "easy",
    type: "selfcare",
  },
  {
    id: 12,
    task: "Clean Room",
    description: "Organize and clean the room",
    difficulty: "medium",
    type: "other",
  },
  {
    id: 13,
    task: "Laundry",
    description: "Wash clothes",
    difficulty: "easy",
    type: "other",
  },
  {
    id: 14,
    task: "Meal Prep",
    description: "Prepare meals for the week",
    difficulty: "hard",
    type: "selfcare",
  },
  {
    id: 15,
    task: "Check Emails",
    description: "Read and respond to important emails",
    difficulty: "easy",
    type: "work",
  },
  {
    id: 16,
    task: "Research Topic",
    description: "Gather information on project topic",
    difficulty: "medium",
    type: "study",
  },
  {
    id: 17,
    task: "Yoga",
    description: "Do a 15-minute yoga session",
    difficulty: "easy",
    type: "selfcare",
  },
  {
    id: 18,
    task: "Organize Files",
    description: "Arrange documents in order",
    difficulty: "medium",
    type: "work",
  },
  {
    id: 19,
    task: "Write Report",
    description: "Draft a summary of the week's work",
    difficulty: "hard",
    type: "work",
  },
  {
    id: 20,
    task: "Social Media Break",
    description: "Stay offline for the day",
    difficulty: "easy",
    type: "selfcare",
  },
  {
    id: 21,
    task: "Learn a New Recipe",
    description: "Try cooking a new dish",
    difficulty: "medium",
    type: "other",
  },
  {
    id: 22,
    task: "Work on Presentation",
    description: "Prepare slides for upcoming presentation",
    difficulty: "medium",
    type: "work",
  },
  {
    id: 23,
    task: "Organize Desk",
    description: "Clean and organize workspace",
    difficulty: "easy",
    type: "selfcare",
  },
  {
    id: 24,
    task: "Brainstorm Ideas",
    description: "Think of new project ideas",
    difficulty: "medium",
    type: "work",
  },
  {
    id: 25,
    task: "Budgeting",
    description: "Review and plan monthly expenses",
    difficulty: "hard",
    type: "other",
  },
  {
    id: 26,
    task: "Read an Article",
    description: "Read one article related to project",
    difficulty: "easy",
    type: "study",
  },
  {
    id: 27,
    task: "Listen to Podcast",
    description: "Listen to a motivational podcast",
    difficulty: "easy",
    type: "selfcare",
  },
  {
    id: 28,
    task: "Network",
    description: "Reach out to a professional contact",
    difficulty: "medium",
    type: "work",
  },
  {
    id: 29,
    task: "Organize Closet",
    description: "Sort out old clothes and reorganize",
    difficulty: "medium",
    type: "other",
  },
  {
    id: 30,
    task: "Mind Mapping",
    description: "Create a mind map for project ideas",
    difficulty: "easy",
    type: "study",
  },
  {
    id: 31,
    task: "Gardening",
    description: "Water plants and prune garden",
    difficulty: "easy",
    type: "selfcare",
  },
  {
    id: 32,
    task: "Financial Planning",
    description: "Review financial goals and investments",
    difficulty: "hard",
    type: "other",
  },
  {
    id: 33,
    task: "Create Playlist",
    description: "Make a playlist of favorite songs",
    difficulty: "easy",
    type: "selfcare",
  },
  {
    id: 34,
    task: "Skill Practice",
    description: "Spend an hour practicing a skill",
    difficulty: "medium",
    type: "study",
  },
  {
    id: 35,
    task: "Write Code",
    description: "Work on personal coding project",
    difficulty: "hard",
    type: "work",
  },
  {
    id: 36,
    task: "Draw or Paint",
    description: "Create an artwork",
    difficulty: "medium",
    type: "other",
  },
  {
    id: 37,
    task: "Volunteer",
    description: "Help at a community event",
    difficulty: "medium",
    type: "selfcare",
  },
  {
    id: 38,
    task: "Complete Survey",
    description: "Participate in a research survey",
    difficulty: "easy",
    type: "study",
  },
  {
    id: 39,
    task: "Work on Proposal",
    description: "Draft a proposal for new project",
    difficulty: "hard",
    type: "work",
  },
  {
    id: 40,
    task: "Sleep Early",
    description: "Aim to sleep 8 hours",
    difficulty: "easy",
    type: "selfcare",
  },
];

export default tasks;
